    name: Deploy Backend to AWS Elastic Beanstalk

    on:
      push:
        branches:
          - main # Or your deployment branch
        paths:
          - 'packages/backend/**'
          - 'packages/shared/**'
          - '.github/workflows/backend-deploy.yml'
          # Exclude changes within .ebextensions from triggering a build-only deploy
          # if you want to deploy config changes separately/manually sometimes
          # - '!packages/backend/.ebextensions/**'

    jobs:
      deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Setup Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '22' # Use your project's Node.js version

          - name: Setup pnpm
            uses: pnpm/action-setup@v4
            with:
              version: 10.7.1 # Or your pnpm version

          - name: Install dependencies
            run: pnpm install --frozen-lockfile

          - name: Build shared package
            run: pnpm --filter @collabx/shared build

          - name: Build backend package
            run: pnpm --filter @collabx/backend build

          - name: Generate deployment package
            run: |
              cd packages/backend
              # Install and build dependencies before zipping
              pnpm install
              # Create deployment package with node_modules
              zip -r ../../deploy.zip dist Procfile .ebextensions .platform package.json node_modules
              cd ../..

          - name: Configure AWS Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}

          - name: Deploy to Elastic Beanstalk
            uses: einaregilsson/beanstalk-deploy@v21
            with:
              aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              application_name: ${{ secrets.EB_APPLICATION_NAME }}
              environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
              version_label: "backend-${{ github.sha }}" # Unique version label
              region: ${{ secrets.AWS_REGION }}
              deployment_package: deploy.zip # The zip file created earlier
              # Use existing version if package hasn't changed (optional optimization)
              # use_existing_version_if_available: true
